apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnet-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dotnet-api
  template:
    metadata:
      labels:
        app: dotnet-api
    spec:
      containers:
        - name: dotnet-api
          image: dotnet-api:local
          ports:
            - containerPort: 8080
          env:
            - name: MONGO_CONN
              value: "mongodb://mongo:27017"
---
apiVersion: v1
kind: Service
metadata:
  name: dotnet-api
spec:
  type: NodePort
  selector:
    app: dotnet-api
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
