apiVersion: apps/v1
kind: Deployment
metadata:
  name: golang-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: golang-api
  template:
    metadata:
      labels:
        app: golang-api
    spec:
      containers:
        - name: golang-api
          image: golang-api:local
          ports:
            - containerPort: 8000
          env:
            - name: MONGO_CONN
              value: "mongodb://mongo:27017"
---
apiVersion: v1
kind: Service
metadata:
  name: golang-api
spec:
  type: NodePort
  selector:
    app: golang-api
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
